apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfactor-demo-dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepfactor-demo-dotnet-app
  template:
    metadata:
      labels:
        app: deepfactor-demo-dotnet-app
    spec:
      containers:
      - name: deepfactor-demo-dotnet-app
        image: dmdeepfactor/deepfactor-demo-dotnet-app:0.0.3
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: deepfactor-demo-dotnet-app
spec:
  type: LoadBalancer
  selector:
    app: deepfactor-demo-dotnet-app
  ports:
  - port: 80
    targetPort: 80

