name: Docker build Pull Requests

on:
  push:
    branches:
    - "!main"
  pull_request:
    branches:
    - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Docker build a PR
        run: |
          docker build -t levelupdevops-pr:${{ github.sha }} .
